# Generated by Django 3.2.7 on 2021-11-09 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_auto_20211014_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='complainmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendType', models.CharField(max_length=36)),
                ('fromId', models.IntegerField(default=0)),
                ('fromName', models.CharField(max_length=36)),
                ('receiveType', models.CharField(max_length=36)),
                ('receiveId', models.IntegerField(default=0)),
                ('receiveName', models.CharField(max_length=36)),
                ('description', models.CharField(max_length=1000)),
                ('curStatus', models.IntegerField(default=0)),
                ('createdTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'complainmsg',
            },
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=12)),
                ('curPeriod', models.SmallIntegerField(default=0)),
                ('curStatus', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='schedules',
            fields=[
                ('sectionNum', models.IntegerField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=36)),
                ('year', models.IntegerField(default=0)),
                ('semester', models.CharField(max_length=36)),
                ('iid', models.IntegerField(default=0)),
                ('days', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=20)),
                ('max_limit', models.SmallIntegerField(default=10)),
                ('current_enroll', models.SmallIntegerField(default=0)),
                ('wait_list', models.SmallIntegerField(default=0)),
                ('status', models.CharField(default='Close', max_length=10)),
                ('rating', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='stuCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(default=0)),
                ('cid', models.IntegerField(default=0)),
                ('sectionNum', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('semester', models.CharField(max_length=36)),
                ('grade', models.CharField(max_length=1)),
                ('curStatus', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'stucourse',
            },
        ),
        migrations.RenameField(
            model_name='course',
            old_name='insName',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='current_enroll',
        ),
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_limit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='wait_list',
        ),
    ]
