# Generated by Django 3.2.7 on 2021-11-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0013_auto_20211109_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='curPeriod',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='period',
            name='curStatus',
            field=models.IntegerField(default=0),
        ),
    ]
