# Generated by Django 3.2.7 on 2021-11-09 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0014_auto_20211109_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='insMsg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('receiverID', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=256)),
                ('getTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'insMsg',
            },
        ),
        migrations.CreateModel(
            name='stuMsg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('receiverID', models.IntegerField(default=0)),
                ('sender', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=256)),
                ('getTime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'stuMsg',
            },
        ),
        migrations.AlterModelTable(
            name='period',
            table='period',
        ),
    ]
